require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PrivateMessagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PrivateMessage. As you add validations to PrivateMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrivateMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all private_messages as @private_messages" do
      private_message = PrivateMessage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:private_messages)).to eq([private_message])
    end
  end

  describe "GET #show" do
    it "assigns the requested private_message as @private_message" do
      private_message = PrivateMessage.create! valid_attributes
      get :show, {:id => private_message.to_param}, valid_session
      expect(assigns(:private_message)).to eq(private_message)
    end
  end

  describe "GET #new" do
    it "assigns a new private_message as @private_message" do
      get :new, {}, valid_session
      expect(assigns(:private_message)).to be_a_new(PrivateMessage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested private_message as @private_message" do
      private_message = PrivateMessage.create! valid_attributes
      get :edit, {:id => private_message.to_param}, valid_session
      expect(assigns(:private_message)).to eq(private_message)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PrivateMessage" do
        expect {
          post :create, {:private_message => valid_attributes}, valid_session
        }.to change(PrivateMessage, :count).by(1)
      end

      it "assigns a newly created private_message as @private_message" do
        post :create, {:private_message => valid_attributes}, valid_session
        expect(assigns(:private_message)).to be_a(PrivateMessage)
        expect(assigns(:private_message)).to be_persisted
      end

      it "redirects to the created private_message" do
        post :create, {:private_message => valid_attributes}, valid_session
        expect(response).to redirect_to(PrivateMessage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved private_message as @private_message" do
        post :create, {:private_message => invalid_attributes}, valid_session
        expect(assigns(:private_message)).to be_a_new(PrivateMessage)
      end

      it "re-renders the 'new' template" do
        post :create, {:private_message => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested private_message" do
        private_message = PrivateMessage.create! valid_attributes
        put :update, {:id => private_message.to_param, :private_message => new_attributes}, valid_session
        private_message.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested private_message as @private_message" do
        private_message = PrivateMessage.create! valid_attributes
        put :update, {:id => private_message.to_param, :private_message => valid_attributes}, valid_session
        expect(assigns(:private_message)).to eq(private_message)
      end

      it "redirects to the private_message" do
        private_message = PrivateMessage.create! valid_attributes
        put :update, {:id => private_message.to_param, :private_message => valid_attributes}, valid_session
        expect(response).to redirect_to(private_message)
      end
    end

    context "with invalid params" do
      it "assigns the private_message as @private_message" do
        private_message = PrivateMessage.create! valid_attributes
        put :update, {:id => private_message.to_param, :private_message => invalid_attributes}, valid_session
        expect(assigns(:private_message)).to eq(private_message)
      end

      it "re-renders the 'edit' template" do
        private_message = PrivateMessage.create! valid_attributes
        put :update, {:id => private_message.to_param, :private_message => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested private_message" do
      private_message = PrivateMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => private_message.to_param}, valid_session
      }.to change(PrivateMessage, :count).by(-1)
    end

    it "redirects to the private_messages list" do
      private_message = PrivateMessage.create! valid_attributes
      delete :destroy, {:id => private_message.to_param}, valid_session
      expect(response).to redirect_to(private_messages_url)
    end
  end

end
